### ISSUE TITLE
Downloading the assets of a specific release

### ISSUE THREAD

**Issue by orhun** [devmatteini/dra#3]
Hello!

I know, the project description is "Download an asset from the **latest** GitHub release" but I wanted to ask nevertheless: are you thinking of adding an argument (e.g. `--release <TAG>`) for making it possible to download the assets of a specific release? If you're thinking of implementing this, I'd be happy to submit a PR about it. If not, feel free to close the issue 🙂 

Thank you! 🐻

**Comment by devmatteini** [comment]
Hi @orhun! Sorry for the late reply...

Yes, I was thinking on adding something like that. I would use `--tag` option instead of `--release`, but the functionality is exactly the same.

If you still would like to work on this issue please have a look at the new [CONTRIBUTING.md](https://github.com/devmatteini/dra/blob/main/CONTRIBUTING.md) that I recently finished.

---

Regarding the implementation I think it would only make sense to use this new option with `dra-download` sub command. The `dra-untag` is only useful when you want to download from the latest release.
If you have any other idea let's talk about it!
